export default {
  All_Universe: "All Universe",
  Ana_Vingada: "Ana Vingada.",
  and: "and",
  API: "API",
  Average_height: "Average height",
  Average_lifespan: "Average lifespan",
  Background: "Background",
  Birth_Year: "Birth Year",
  Cargo_Capacity: "Cargo Capacity",
  character: "character",
  Characteristics: "Characteristics",
  characters: "characters",
  Characters: "Characters",
  Class: "Class",
  Classification: "Classification",
  Climate: "Climate",
  Consumables: "Consumables",
  Contact_Me: "contact me",
  Contact: "Contact",
  Cost_credits: "Cost in credits",
  Crew: "Crew",
  Designation: "Designation",
  Diameter: "Diameter",
  Director: "Director",
  English: "English",
  Episode: "Episode",
  Error: "Error",
  Eye_color: "Eye color",
  Find_More_SW_Universe: "Find more about the Star Wars Universe",
  Gender: "Gender",
  Go_Homepage: "Go to the Homepage",
  Gravity: "Gravity",
  Hair_color: "Hair color",
  Height: "Height",
  here: "here",
  Hyperdrive_Rating: "Hyperdrive Rating",
  If_Questions: "If you have any questions, please",
  Images: "Images",
  Language: "Language",
  Length: "Length",
  Loading_: "Loading...",
  Logo: "Logo",
  Manufacturer: "Manufacturer",
  Mass: "Mass",
  Material_Sources: "Material Sources",
  Materials_Intro: "This web app was built with Vue and used resources available on the internet. Please find below all references to the used resources.",
  Materials: "Materials",
  Maximum_Speed: "Maximum Speed",
  MGLT: "MGLT",
  Model: "Model",
  movie: "movie",
  movies: "movies",
  Movies: "Movies",
  No_Characters: "No characters found!",
  No_Movies: "No movies found!",
  No_Page: "Page not found",
  No_Planets: "No planets found!",
  No_Spaceships: "No spaceships found!",
  No_Species: "No species found!",
  No_Vehicles: "No vehicles found!",
  Obs_Api: "From Swapi. This API provides all the Star Wars Data in all pages of this web.",
  Obs_Background: "From Wikimedia. Background image used in all the web.",
  Obs_Characters: "From tumblr.com. Image used in the SW Universe page for characters reference.",
  Obs_Logo: "From Wikimedia. Star Wars logo used in the header.",
  Obs_Movies: "From miro.medium.com. Image used in the the SW Universe page for movies reference.",
  Obs_Planets: "From virtualbackgrounds.site. Image used in the the SW Universe page for planets reference.",
  Obs_Spaceships: "From media-amazon.com. Image used in the the SW Universe page for spaceships reference.",
  Obs_Species: "From tvovermind.com. Image used in the the SW Universe page for species reference.",
  Obs_Vehicles: "From mvsnoticias.com. Image used in the the SW Universe page for vehicles reference.",
  Oops: "Oops",
  Orbital_Period: "Orbital Period",
  Page: "Page",
  Passengers: "Passengers",
  Pilots: "Pilots",
  Planet_Origin: "Planet of origin",
  planet: "planet",
  planets: "planets",
  Planets: "Planets",
  Population: "Population",
  Portuguese: "Portuguese",
  Poster_Characters: "Characters` poster",
  Poster_Movies: "Movies` poster",
  Poster_Planets: "Planets` poster",
  Poster_Spaceships: "Spaceships` poster",
  Poster_Species: "Species` poster",
  Poster_Vehicles: "Vehicles` poster",
  Producer_s: "Producer(s)",
  Redirected_In: "You'll be redirected to the homepage in",
  Release_date: "Release date",
  Residents: "Residents",
  Resources_referenced: "All resources are referenced",
  Return_To: "Return to",
  Rights_Reserved: "All rights reserved.",
  Rotarion_Period: "Rotarion Period",
  Run_Search_On: "Run a google search on this",
  Skin_color: "Skin color",
  Skin_colors: "Skin colors",
  Something_Wrong: "Something went wrong.",
  spaceship: "spaceship",
  spaceships: "spaceships",
  Spaceships: "Spaceships",
  Spanish: "Spanish",
  specie: "specie",
  species: "species",
  Species: "Species",
  StarWars_Universe: "Star Wars Universe",
  Surface_Water: "Surface Water",
  SW_API: "Star Wars API",
  SW_App: "Star Wars Vue App.",
  SW_Characters: "Star Wars Characters",
  SW_Logo: "Star Wars Logo",
  SW_Movies: "Star Wars Movies",
  SW_Planets: "Star Wars Planets",
  SW_Spaceships: "Star Wars Spaceships",
  SW_Species: "Star Wars Species",
  SW_Universe: "SW Universe",
  SW_Vehicles: "Star Wars Vehicles",
  Terrain: "Terrain",
  Thank_You: "Thank you",
  The_Characters: "The Characters",
  The_Movies: "The Movies",
  The_Planets: "The Planets",
  The_Spaceships: "The Spaceships",
  The_Species: "The Species",
  The_Vehicles: "The Vehicles",
  Total_Of: "Total of",
  vehicle: "vehicle",
  vehicles: "vehicles",
  Vehicles: "Vehicles",
  View: "View",
  Welcome: "Welcome",
}