export default {
    All_Universe: "Todo o Universo",
    Ana_Vingada: "Ana Vingada.",
    and: "e",
    API: "API",
    Average_height: "Altura média",
    Average_lifespan: "Esperança média de vida",
    Background: "Fundo",
    Birth_Year: "Ano de nascimento",
    Cargo_Capacity: "Capacidade de carga",
    character: "personagem",
    Characteristics: "características",
    characters: "personagens",
    Characters: "Personagens",
    Class: "Classe",
    Classification: "Classificação",
    Climate: "Clima",
    Consumables: "Consumíveis",
    Contact_Me: "contacta-me",
    Contact: "Contacto",
    Cost_credits: "Custo em créditos",
    Crew: "Tripulação",
    Designation: "Designação",
    Diameter: "Diâmetro",
    Director: "Director",
    English: "Inglês",
    Episode: "Episódio",
    Error: "Erro",
    Eye_color: "Cor dos olhos",
    Find_More_SW_Universe: "Sabe mais sobre o Universo de Star Wars",
    Gender: "Gênero",
    Go_Homepage: "Ir para a Homepage",
    Gravity: "Gravidade",
    Hair_color: "Cor de cabelo",
    Height: "Altura",
    here: "aqui",
    Hyperdrive_Rating: "Avaliação da Hyperdrive",
    If_Questions: "Se tiveres alguma questão, por favor",
    Images: "Imagens",
    Language: "Língua",
    Length: "Comprimento",
    Loading_: "A carregar...",
    Logo: "Logo",
    Manufacturer: "Fabricante",
    Mass: "Massa",
    Material_Sources: "Fontes de recursos",
    Materials_Intro: "Esta aplicação web foi construída com Vue e recursos disponíveis na Internet. Podes encontrar a referência de todos os recursos aqui.",
    Materials: "Recursos",
    Maximum_Speed: "Velocidade máxima",
    MGLT: "MGLT",
    Model: "Modelo",
    movie: "filme",
    movies: "filmes",
    Movies: "Filmes",
    No_Characters: "Não se encontraram personagens!",
    No_Movies: "Não se encontraram filmes!",
    No_Page: "Página não encontrada",
    No_Planets: "Não se encontraram planetas!",
    No_Spaceships: "Não se encontraram naves espaciais!",
    No_Species: "Não se encontraram espécies!",
    No_Vehicles: "Não se encontraram veículos!",
    Obs_Api: "De Swapi. Esta API contém todos os dados de Star Wars desta aplicação.",
    Obs_Background: "De Wikimedia. Imagem de fundo usada em toda a web.",
    Obs_Characters: "De tumblr.com. Imagem usada na página do Universo SW como referência às personagens.",
    Obs_Logo: "De Wikimedia. Logo de Star Wars usado no header.",
    Obs_Movies: "De miro.medium.com. Imagem usada na página do Universo SW como referência aos filmes.",
    Obs_Planets: "De virtualbackgrounds.site. Imagem usada na página do Universo SW como referência aos planetas.",
    Obs_Spaceships: "De media-amazon.com. Imagem usada na página do Universo SW como referência às naves espaciais.",
    Obs_Species: "De tvovermind.com. Imagem usada na página do Universo SW como referência às espécies.",
    Obs_Vehicles: "De mvsnoticias.com. Imagem usada na página do Universo SW como referência aos veículos.",
    Oops: "Oops",
    Orbital_Period: "Período de órbita",
    Page: "Página",
    Passengers: "Passageiros",
    Pilots: "Pilotos",
    Planet_Origin: "Planeta de origem",
    planet: "planeta",
    planets: "planetas",
    Planets: "Planetas",
    Population: "População",
    Portuguese: "Português",
    Poster_Characters: "Poster de Personagens",
    Poster_Movies: "Poster de Filmes",
    Poster_Planets: "Poster de Planetas",
    Poster_Spaceships: "Poster de Naves Espaciais",
    Poster_Species: "Poster de Espécies",
    Poster_Vehicles: "Poster de Veículos",
    Producer_s: "Produtor(es)",
    Redirected_In: "Vais ser redireccionado para a homepage em",
    Release_date: "Data de estreia",
    Residents: "Residentes",
    Resources_referenced: "Todos os recursos estão referenciados",
    Return_To: "Voltar a",
    Rights_Reserved: "Todos os direitos reservados.",
    Rotarion_Period: "Período de rotação",
    Run_Search_On: "Faz uma pesquisa no Google sobre este(a)",
    Skin_color: "Cor de pele",
    Skin_colors: "Cores de pele",
    Something_Wrong: "Alguma coisa correu mal.",
    spaceship: "nave",
    spaceships: "naves",
    Spaceships: "Naves",
    Spanish: "Espanhol",
    specie: "espécie",
    species: "espécies",
    Species: "Espécies",
    StarWars_Universe: "Universo Star Wars",
    Surface_Water: "Água em superfície",
    SW_API: "API Star Wars",
    SW_App: "Star Wars Vue App.",
    SW_Characters: "Personagens de Star Wars",
    SW_Logo: "Logo de Star Wars",
    SW_Movies: "Filmes de Star Wars",
    SW_Planets: "Planetas de Star Wars",
    SW_Spaceships: "Naves de Star Wars",
    SW_Species: "Espécies de Star Wars",
    SW_Universe: "Universo SW",
    SW_Vehicles: "Veículos de Star Wars",
    Terrain: "Terreno",
    Thank_You: "Obrigado",
    The_Characters: "As Personagens",
    The_Movies: "Os Filmes",
    The_Planets: "Os Planetas",
    The_Spaceships: "As Naves",
    The_Species: "As Espécies",
    The_Vehicles: "Os Veículos",
    Total_Of: "Total de ",
    vehicle: "veículo",
    vehicles: "veículos",
    Vehicles: "Veículos",
    View: "Ver",
    Welcome: "Bem-vindo(a)",
}