export default {
    All_Universe: "Todo el Universo",
    Ana_Vingada: "Ana Vingada.",
    and: "y",
    API: "API",
    Average_height: "Altura media",
    Average_lifespan: "Esperanza media de vida",
    Background: "Fondo",
    Birth_Year: "Año de nacimiento",
    Cargo_Capacity: "Capacidad de carga",
    character: "personaje",
    Characteristics: "caracteristicas",
    characters: "personajes",
    Characters: "Personajes",
    Class: "Clase",
    Classification: "Classificación",
    Climate: "Clima",
    Consumables: "Consumibles",
    Contact_Me: "contáctame",
    Contact: "Contacto",
    Cost_credits: "Costo en creditos",
    Crew: "Tripulación",
    Designation: "Designación",
    Diameter: "Diámetro",
    Director: "Director",
    English: "Inglés",
    Episode: "Episodio",
    Error: "Erroe",
    Eye_color: "Color de ojos",
    Find_More_SW_Universe: "Sabe más sobre el Universo de Star Wars",
    Gender: "Género",
    Go_Homepage: "Ir para la Homepage",
    Gravity: "Gravidad",
    Hair_color: "Color del pelo",
    Height: "Altura",
    here: "aquí",
    Hyperdrive_Rating: "Avaliación de la Hyperdrive",
    If_Questions: "Si tienes alguna cuestión, por favor",
    Images: "Imágenes",
    Language: "Lengua",
    Length: "Longitud",
    Loading_: "Cargando...",
    Logo: "Logo",
    Manufacturer: "Fabricante",
    Mass: "Masa",
    Material_Sources: "Fuentes de recursos",
    Materials_Intro: "Esta aplicación web fue construida con Vue y recursos disponibles en Internet. Puedes encontrar la referencia de todos los recursos aquí.",
    Materials: "Recursos",
    Maximum_Speed: "Velocidad maxima",
    MGLT: "MGLT",
    Model: "Modelo",
    movie: "película",
    movies: "películas",
    Movies: "Películas",
    No_Characters: "No se han encontrado personajes!",
    No_Movies: "No se han encontrado películas!",
    No_Page: "Página no encontrada",
    No_Planets: "No se han encontrado planetas!",
    No_Spaceships: "No se han encontrado naves espaciales!",
    No_Species: "No se han encontrado especies!",
    No_Vehicles: "No se han encontrado vehículos!",
    Obs_Api: "De Swapi. Esta API contiene todos los datos de Star Wars de esta aplicación.",
    Obs_Background: "De Wikimedia. Imagem de fondo usada en toda la web.",
    Obs_Characters: "De tumblr.com. Imagem usada en la página del Universo SW como referencia a los personajes.",
    Obs_Logo: "De Wikimedia. Logo de Star Wars usado en el header.",
    Obs_Movies: "De miro.medium.com. Imagem usada en la página del Universo SW como referencia a las películas.",
    Obs_Planets: "De virtualbackgrounds.site. Imagem usada en la página del Universo SW como referencia a los planetas.",
    Obs_Spaceships: "De media-amazon.com. Imagem usada en la página del Universo SW como referencia a las naves espaciales.",
    Obs_Species: "De tvovermind.com. Imagem usada en la página del Universo SW como referencia a las especies.",
    Obs_Vehicles: "De mvsnoticias.com. Imagem usada en la página del Universo SW como referencia a los vehículos.",
    Oops: "Oops",
    Orbital_Period: "Período de orbita",
    Page: "Página",
    Passengers: "Pasajeros",
    Pilots: "Pilotos",
    Planet_Origin: "Planeta de origen",
    planet: "planeta",
    planets: "planetas",
    Planets: "Planetas",
    Population: "Populación",
    Portuguese: "Portugués",
    Poster_Characters: "Poster de Personajes",
    Poster_Movies: "Poster de Películas",
    Poster_Planets: "Poster de Planetas",
    Poster_Spaceships: "Poster de Naves Espaciales",
    Poster_Species: "Poster de Especies",
    Poster_Vehicles: "Poster de Vehículos",
    Producer_s: "Productor(es)",
    Redirected_In: "Vas a ser redireccionado para la homepage en",
    Release_date: "Fecha de estreno",
    Residents: "Residentes",
    Resources_referenced: "Todos los recursos están referenciados",
    Return_To: "Volver a",
    Rights_Reserved: "Todos los derechos reservados.",
    Rotarion_Period: "Período de rotación",
    Run_Search_On: "Haz una búsqueda en Google sobre este(a)",
    Skin_color: "Color de piel",
    Skin_colors: "Colores de piel",
    Something_Wrong: "Algo ha ido mal.",
    spaceship: "nave",
    spaceships: "naves",
    Spaceships: "Naves",
    Spanish: "Castellano",
    specie: "especie",
    species: "especies",
    Species: "Especies",
    StarWars_Universe: "Universo Star Wars",
    Surface_Water: "Água en superficie",
    SW_API: "API Star Wars",
    SW_App: "Star Wars Vue App.",
    SW_Characters: "Personajes de Star Wars",
    SW_Logo: "Logo de Star Wars",
    SW_Movies: "Películas de Star Wars",
    SW_Planets: "Planetas de Star Wars",
    SW_Spaceships: "Naves de Star Wars",
    SW_Species: "Especies de Star Wars",
    SW_Universe: "Universo SW",
    SW_Vehicles: "Vehículos de Star Wars",
    Terrain: "Terreno",
    Thank_You: "Gracias",
    The_Characters: "Los Personajes",
    The_Movies: "Las Películas",
    The_Planets: "Los Planetas",
    The_Spaceships: "Las Naves",
    The_Species: "Las Especies",
    The_Vehicles: "Los Vehículos",
    Total_Of: "Total de ",
    vehicle: "vehículo",
    vehicles: "vehículos",
    Vehicles: "Vehículos",
    View: "Ver",
    Welcome: "Bienvenido(a)",
}